#!/bin/sh
#
# Startup script for Main
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export APPNAME=MyInstagram
export HOME=/home/haipn/NetBeansProjects/MyInstagram
export PORT=8084
export APP_ENV=production
export XMX=2G
export CONF=conf
export JARFILE=$HOME/dist/MyInstagram.jar
export FUNCTION_MAIN=httpservice.WebServer
cd $HOME
pid_file=tmp/$APPNAME.pid
log_file=tmp/$APPNAME.log

# Arguments to pass to the JVM
JVM_OPTS=" \
        -Dappname=$APPNAME \
        -Xmx$XMX \
        -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8085 \
        -XX:SurvivorRatio=8 \
        -XX:+UseParNewGC \
        -XX:+UseConcMarkSweepGC \
        -XX:+CMSParallelRemarkEnabled \
        -XX:MaxTenuringThreshold=1 \
        -XX:CMSInitiatingOccupancyFraction=75 \
        -XX:+UseCMSInitiatingOccupancyOnly \
        -XX:+HeapDumpOnOutOfMemoryError \
        -Dzport=$PORT \
        -Dappconfig=$HOME/$CONF \
        -Dapppath=. \
	-Denvironment=$APP_ENV"


if [ -x $JAVA_HOME/bin/java ]; then
    JAVA=$JAVA_HOME/bin/java
else
    JAVA=`which java`
fi

case "$1" in
    start)
        # Main startup
        echo -n "Starting $APPNAME (port $PORT): "
        exec $JAVA $JVM_OPTS -cp $JARFILE $FUNCTION_MAIN > $log_file 2>&1 &
	[ ! -z $pid_file ] && printf "%d" $! > $pid_file
        echo "OK"
        ;;
    stop)
        # Main shutdown
        echo -n "Shutdown $APPNAME (port $PORT): "
        kill `cat $pid_file`
        echo "OK"
        ;;
    reload|restart)
        $0 stop
	sleep 1
        $0 start
        ;;
    status)
        ;;
    *)
        echo "Usage: `basename $0` start|stop|restart|reload"
        exit 1
esac

exit 0
