/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity.DAO;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author generated by haipn
 */
public class AccountEntity {
    public int id;
    public String userId;
    

    public AccountEntity(ResultSet rs) {
        try {
            this.id = rs.getInt("id");
            this.userId = rs.getString("user_id");
            
        } catch (SQLException ex) {
        }
    }

    public int setParameters(PreparedStatement stmt, int idx) {
        try {
            if (stmt == null) {
                return idx;
            }
            stmt.setInt(idx++, id);
            stmt.setString(idx++, userId);
            
        } catch (SQLException ex) {
        }
        return idx;
    }

    public int setPrimaryKeyParameters(PreparedStatement stmt, int idx) {
        try {
            if (stmt == null) {
                return idx;
            }
            stmt.setInt(idx++, id);
            
        } catch (SQLException ex) {
        }
        return idx;
    }

    public int setParametersForUpdate(PreparedStatement stmt, int idx) {
        try {
            if (stmt == null) {
                return idx;
            }
            stmt.setString(idx++, userId);
            stmt.setInt(idx++, id);
                     
            idx = setPrimaryKeyParameters(stmt, idx);
        } catch (SQLException ex) {
        }
        return idx;
    }
}
