/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity.DAO;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author generated by haipn
 */
public class LikeImageEntity {

    public String userId;
    public int imageId;
    public int action;
    public long timestamp;

    public LikeImageEntity(String userId, int imageId, int action, long timestamp) {
        this.userId = userId;
        this.imageId = imageId;
        this.action = action;
        this.timestamp = timestamp;
    }

    public LikeImageEntity(ResultSet rs) {
        try {
            userId = rs.getString("user_id");
            imageId = rs.getInt("image_id");
            action = rs.getInt("action");
            timestamp = rs.getLong("timestamp");
        } catch (SQLException ex) {
        }
    }

    public int setParameters(PreparedStatement stmt, int idx) {
        try {
            if (stmt == null) {
                return idx;
            }
            stmt.setString(idx++, userId);
            stmt.setInt(idx++, imageId);
            stmt.setInt(idx++, action);
            stmt.setLong(idx++, timestamp);
        } catch (SQLException ex) {
        }
        return idx;
    }

    public int setPrimaryKeyParameters(PreparedStatement stmt, int idx) {
        try {
            if (stmt == null) {
                return idx;
            }
            stmt.setString(idx++, userId);
            stmt.setInt(idx++, imageId);
        } catch (SQLException ex) {
        }
        return idx;
    }

    public int setParametersForUpdate(PreparedStatement stmt, int idx) {
        try {
            if (stmt == null) {
                return idx;
            }
            stmt.setInt(idx++, action);
            stmt.setLong(idx++, timestamp);
            stmt.setString(idx++, userId);
            stmt.setInt(idx++, imageId);
        } catch (SQLException ex) {
        }
        return idx;
    }
}
