/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity.DAO;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author generated by haipn
 */
public class TranscriptEntity {
    public int id;
    public String mssv;
    public String subjectId;
    public String subjectName;
    public int nCredits;
    public String className;
    public float midTermMark;
    public float mark;

    public TranscriptEntity(int id, String mssv, String subjectId, String subjectName, int nCredits, String className, float midTermMark, float mark) {
        this.id = id;
        this.mssv = mssv;
        this.subjectId = subjectId;
        this.subjectName = subjectName;
        this.nCredits = nCredits;
        this.className = className;
        this.midTermMark = midTermMark;
        this.mark = mark;
    }
    

    public TranscriptEntity(ResultSet rs) {
        try {
            this.id = rs.getInt("id");
            this.mssv = rs.getString("mssv");
            this.subjectId = rs.getString("subject_id");
            this.subjectName = rs.getString("subject_name");
            this.nCredits = rs.getInt("n_credits");
            this.className = rs.getString("class_name");
            this.midTermMark = rs.getFloat("mid_term_mark");
            this.mark = rs.getFloat("mark");
            
        } catch (SQLException ex) {
        }
    }

    public int setParameters(PreparedStatement stmt, int idx) {
        try {
            if (stmt == null) {
                return idx;
            }
            stmt.setString(idx++, mssv);
            stmt.setString(idx++, subjectId);
            stmt.setString(idx++, subjectName);
            stmt.setInt(idx++, nCredits);
            stmt.setString(idx++, className);
            stmt.setFloat(idx++, midTermMark);
            stmt.setFloat(idx++, mark);
            
        } catch (SQLException ex) {
        }
        return idx;
    }

    public int setPrimaryKeyParameters(PreparedStatement stmt, int idx) {
        try {
            if (stmt == null) {
                return idx;
            }
            stmt.setInt(idx++, id);
            
        } catch (SQLException ex) {
        }
        return idx;
    }

    public int setParametersForUpdate(PreparedStatement stmt, int idx) {
        try {
            if (stmt == null) {
                return idx;
            }
            stmt.setString(idx++, mssv);
            stmt.setString(idx++, subjectId);
            stmt.setString(idx++, subjectName);
            stmt.setInt(idx++, nCredits);
            stmt.setString(idx++, className);
            stmt.setFloat(idx++, midTermMark);
            stmt.setFloat(idx++, mark);
            stmt.setInt(idx++, id);
                     
            idx = setPrimaryKeyParameters(stmt, idx);
        } catch (SQLException ex) {
        }
        return idx;
    }

    @Override
    public String toString() {
        return String.format("%s|%s|%s|%s|%s|%s|%s|%s", id, mssv, subjectId, subjectName, nCredits, className, midTermMark, mark);
    }
}
